### ISSUE TITLE
"base" in `make_headers.sh` is not determined correctly

### ISSUE THREAD

**Issue by rgommers** [scipy/boost-headers-only#2]
This should use some local tempfile, not `/usr/bin/`:

```
$ source make_headers.sh
Downloading source distribution of Boost 1.75.0... 
/usr/bin/boost.1.75.0.tar.gz: Permission denied
Unpacking... tar (child): /usr/bin/boost.1.75.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Extracted!
Starting configure... bash: cd: /usr/bin/boost_1_75_0: No such file or directory
Failed to run Boost ./bootstrap.sh!
```

**Comment by mckib2** [comment]
Yes, I was aware that the simple method I used to determine the script's directory was not foolproof, i.e. [this line](https://github.com/scipy/boost-headers-only/blob/ca02b3b71579fe4913e3e4d1153c34868ec95769/make_headers.sh#L13) in `make_headers.sh`:
```bash
base="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
```

> This should use some local tempfile

I agree, `/tmp/` would be a better place for this
